basePath: /
consumes:
    - application/json
info:
    description: '# Documentation for Product API'
    title: of Product API
    version: 1.0.0
paths:
    /products:
        get:
            description: Returns the list of products
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
            tags:
                - products
produces:
    - application/json
responses:
    productsResponse:
        description: A list of products returned in the response
        schema:
            items: {}
            type: array
schemes:
    - HTTP
swagger: "2.0"
